feat(login): add optional login feature
grski/chat-ui pull request #12
Opened 2023-06-08 06:23 UTC by martwozniak

2023-06-21 07:37 UTC, grski commented
fix conflicts pls

2023-06-21 12:59 UTC, grski requested changes
resolve conflicts

2023-06-23 10:59 UTC, grski commented
@martwozniak conflicts still

2023-06-23 12:32 UTC, martwozniak commented
resolved?

2023-06-23 13:47 UTC, grski commented
![image](https://github.com/grski/chat-ui/assets/16924479/8fa3690b-2117-43be-8ef6-3457501678dd)

2023-06-23 13:47 UTC, grski approved these changes

2023-06-26 05:12 UTC, merged