feat(chat): Add persistence to selected plugin
grski/chat-ui pull request #18
Opened 2023-06-19 08:50 UTC by martwozniak

2023-06-21 12:58 UTC, grski commented on components/Chat/ChatInput.tsx
> +    //setPlugin(null);
leaving commented code is considered bad practice usually

2023-06-21 12:58 UTC, grski requested changes
as in the comment above

2023-06-22 03:41 UTC, martwozniak commented
Updated as recommended

2023-06-23 11:00 UTC, grski approved these changes

2023-06-23 12:30 UTC, merged